# Vagrantfile with multiple machines
ENV["VAGRANT_BOX_UPDATE_CHECK_DISABLE"]	  = "yes"
ENV["VAGRANT_NO_PARALLEL"] = "no"

Vagrant.configure("2") do |config|
    # General Vagrant configuration
    config.vm.box_check_update = false
    config.vm.synced_folder ".", "/vagrant", disabled: true
    config.vm.provider "virtualbox" do |vb|
        vb.gui = false
        vb.cpus = "1"
        vb.memory = "1024"
    end

    # Ubuntu machine configuration
    config.vm.define "ubuntu", primary: false do |ubuntu|
        ubuntu.vm.box = "generic/ubuntu2204"
        ubuntu.vm.box_version = "4.3.12"
        ubuntu.vm.hostname = "ubuntu"
        ubuntu.vm.network "public_network", ip: "192.168.1.21"
        ubuntu.vm.provider "virtualbox" do |vb|
            vb.name = "ubuntu"
            vb.memory = "2048"
            vb.cpus = 1
        end
    end

    # CentOS machine configuration
    config.vm.define "centos", primary: false do |centos|
        centos.vm.box = "centos/stream10"
        centos.vm.box_version = "20250422.0"
        centos.vm.hostname = "centos"
        centos.vm.network "public_network", ip: "192.168.1.84"
        centos.vm.provider "virtualbox" do |vb|
            vb.name = "centos"
            vb.memory = "2048"
            vb.cpus = 1
        end
    end

    # Opensuse machine configuration
    config.vm.define "opensuse", primary: false do |opensuse|
        opensuse.vm.box = "opensuse/Leap-15.2.x86_64"
        opensuse.vm.box_version = "15.2.31.632"
        opensuse.vm.hostname = "opensuse"
        opensuse.vm.network "public_network", ip: "192.168.1.63"
        opensuse.vm.provider "virtualbox" do |vb|
            vb.name = "opensuse"
            vb.memory = "2048"
            vb.cpus = 1
        end
    end

    # Windows machine configuration
    config.vm.define "windows", primary: false do |windows|
        windows.vm.box = "gusztavvargadr/windows-server"
        windows.vm.box_version = "2402.0.2503"
        windows.vm.hostname = "windows"
        windows.vm.network "public_network", ip: "192.168.1.63"
        windows.vm.provider "virtualbox" do |vb|
            vb.name = "windows"
            vb.memory = "2048"
            vb.cpus = 1
        end
    end
end